name: panvimdoc
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/panvimdoc.yml
jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: papis
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): auto generate docs"
          branch: ${{ github.head_ref }}
